### ISSUE TITLE
Triple dash within the body content breaks cybermonday.core/parse-md

### ISSUE THREAD

**Issue by jaketrent** [kiranshila/cybermonday#62]
kiranshila, thanks for the great library.

Triple dash is for front matter, and that works great in most documents. But in the case that the document itself has 3 dashes in it as a part of the content, parsing breaks entirely.

**Comment by kiranshila** [comment]
Great catch! My regex is trying to match the whole document instead of the first line. I'll get a patch together.

**Comment by kiranshila** [comment]
Actually, I'm having trouble reproducing this @jaketrent. Can you provide a MWE?

**Comment by kiranshila** [comment]
Also, I apologize for not seeing this sooner, strangely GitHub didn't notify me of this issue.

**Comment by kiranshila** [comment]
This should be fixed on the latest release
