### ISSUE TITLE
Feature Request: Support for Table of Contents Flexmark Extension

### ISSUE THREAD

**Issue by stelcodes** [kiranshila/cybermonday#63]
Hi there! I'm a big fan of Cybermonday, I'm using it in a [static site generator](https://github.com/stelcodes/nuzzle) I'm working on.

I'm wondering if you'd be open to including support for the [Table of Contents Flexmark Extension](https://github.com/vsch/flexmark-java/wiki/Table-of-Contents-Extension). Basically you just add a line of `[TOC]` or `[TOC levels=1-3]` and you get a table of contents which is just a tree of nested `ul` elements with links to the heading anchors.

I got excited and actually implemented this today, and from what I can tell it works great! Are you interested in adding this extension/feature? I know you want to keep some parity with the CLJS side. I don't have any code for that atm.

**Comment by kiranshila** [comment]
Thanks for the PR, Stel! I've been following your static site generator, which looks so cool! I'll take a look at your PR.
