### ISSUE TITLE
Expand Templating

### ISSUE THREAD

**Issue by kiranshila** [kiranshila/cybermonday#9]
Right now, the templating is very naive, allowing for tagging the most basic mustache-style syntax of `{{foo}}`

I really like the [mustache spec](https://github.com/mustache/spec) and would like to support more of the features. I need to work out how to interleave that into the parsing, for example not templating in preformatted-contexts like code blocks.

Any suggestions on useful behavior, please let me know.

**Comment by kiranshila** [comment]
This would be an expansion of #6

**Comment by tbrooke** [comment]
Wouldn't you want them parsed, but maybe ignored - for example I have someone that has templates that do not involve code so he uses code blocks `stuff` - this becomes a separate node in the AST and I can fairly easily do things like change `stuff` to {{stuff}} (for my non standard use case) or substitute some data like mustache. With default commonmark `  ` would be a code block and {{ }} would be parsed  but  ignored unless you wanted to do something with it and if you didn't it would conform to whatever markdown tag it was in  so in a code block it would display as  -- code {{more code}} code

**Comment by kiranshila** [comment]
Fixed via #20, we'll outsource templates now.
